[package]
name = "tp2-conc"
version = "0.1.0"
authors = ["Alejandro Daneri"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
