[package]
name = "sinonimos"
version = "0.1.0"
authors = ["adaneri <adaneri@fi.uba.ar>", "mlafroce <mlafroce@gmail.com>", "rcasal <rcasal@fi.uba.ar>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = { version = "0.11", features = ["blocking"]}
